"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
var express_1 = require("express");
var CreateListController_1 = require("./controllers/CreateListController.js");
var UpdateListController_1 = require("./controllers/UpdateListController.js");
var DeleteListController_1 = require("./controllers/DeleteListController.js");
var ListListsController_1 = require("./controllers/ListListsController.js");
var CreateCardController_1 = require("./controllers/CreateCardController.js");
var UpdateCardController_1 = require("./controllers/UpdateCardController.js");
var DeleteCardController_1 = require("./controllers/DeleteCardController.js");
var ListCardsController_1 = require("./controllers/ListCardsController.js");
var router = express_1.Router();
var createListController = new CreateListController_1.CreateListController();
var updateListController = new UpdateListController_1.UpdateListController();
var deleteListController = new DeleteListController_1.DeleteListController();
var listListsController = new ListListsController_1.ListListsController();
var createCardController = new CreateCardController_1.CreateCardController();
var updateCardController = new UpdateCardController_1.UpdateCardController();
var deleteCardController = new DeleteCardController_1.DeleteCardController();
var listCardsController = new ListCardsController_1.ListCardsController();
router.post("/lists", createListController.handle);
router.put("/lists", updateListController.handle);
router.delete("/lists", deleteListController.handle);
router.get("/lists", listListsController.handle);
router.post("/cards", createCardController.handle);
router.put("/cards", updateCardController.handle);
router.delete("/cards", deleteCardController.handle);
router.get("/cards", listCardsController.handle);

exports.router = router;
